version: '3.4'

services:
  api-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - api-network
    ports:
      - 3000:3000
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - .:/app:delegated
      - /app/node_modules
  server:
    image: nginx
    restart: always
    ports: 
      - 80:80
    networks:
      - api-network
    depends_on:
      - api-dev
    volumes:
      - ./nginx:/etc/nginx/conf.d
networks:
  api-network: